package com.example.ui.localization

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English 🇬🇧"),
    TURKISH("tr", "Türkçe 🇹🇷"),
    SPANISH("es", "Español 🇪🇸"),
    GERMAN("de", "Deutsch 🇩🇪"),
    FRENCH("fr", "Français 🇫🇷")
}

data class LocalizedStrings(
    val appTitle: String,
    val appSubtitle: String,
    val tabMap: String,
    val tabTasks: String,
    val tabSync: String,
    val settings: String,
    val language: String,
    val languageSubtitle: String,
    val languageSelectHint: String,
    val priority: String,
    val priorityHigh: String,
    val priorityMedium: String,
    val priorityLow: String,
    val enterKeyNewEntry: String,
    val selectedTaskBanner: String,
    val clearSelection: String,
    val addNewTask: String,
    val editTask: String,
    val taskTitleLabel: String,
    val taskTitlePlaceholder: String,
    val taskDescriptionLabel: String,
    val taskDescriptionPlaceholder: String,
    val placeNameLabel: String,
    val placeNamePlaceholder: String,
    val addressLabel: String,
    val categoryLabel: String,
    val radiusLabel: String,
    val searchGoogleMaps: String,
    val searching: String,
    val pinOnMap: String,
    val save: String,
    val cancel: String,
    val emptyTitle: String,
    val emptySubtitle: String,
    val emptyAction: String,
    val permissionTitle: String,
    val permissionSubtitle: String,
    val permissionButton: String,
    val trackingTitle: String,
    val trackingActive: String,
    val trackingInactive: String,
    val trackingIntervalInfo: String,
    val testArrival: String,
    val openInGoogleMaps: String,
    val searchPlaceholder: String,
    val filterAll: String,
    val tasksCount: String,
    val completedCount: String,
    val meterUnit: String,
    val simulatedArrivalToast: String,
    val deleteConfirm: String,
    val proximitySettingTitle: String,
    val proximitySettingSubtitle: String,
    val nearbyAlertTitle: String,
    val nearbyAlertSubtitle: String,
    val showRouteButton: String,
    val openMapsNavigation: String,
    val currentLocationLabel: String,
    val targetLocationLabel: String,
    val walkTimeEstimate: String,
    val noNearbyTasksFound: String,
    val tabArchive: String,
    val archiveTitle: String,
    val archiveSubtitle: String,
    val archiveEmptyTitle: String,
    val archiveEmptySubtitle: String,
    val restoreTask: String,
    val clearArchive: String,
    val clearArchiveConfirm: String,
    val deletePermanently: String,
    val themeSettingTitle: String,
    val themeSettingSubtitle: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val hapticDeleteTip: String,
    val placeNotFoundMessage: (String) -> String,
    val placeFoundSuccess: String,
    val placeLocationNotSetWarning: String,
    val resolveLocation: String
)

object LocalizationManager {

    val english = LocalizedStrings(
        appTitle = "Location Task Manager",
        appSubtitle = "Smart Location & Task Reminder",
        tabMap = "Map",
        tabTasks = "Tasks",
        tabSync = "Sync",
        settings = "Settings",
        language = "App Language",
        languageSubtitle = "Change the interface language instantly",
        languageSelectHint = "Choose preferred language from the list",
        priority = "Priority",
        priorityHigh = "High",
        priorityMedium = "Medium",
        priorityLow = "Low",
        enterKeyNewEntry = "⏎ New Entry",
        selectedTaskBanner = "Selected Task",
        clearSelection = "Deselect",
        addNewTask = "New Location Task",
        editTask = "Edit Task",
        taskTitleLabel = "Task Title",
        taskTitlePlaceholder = "E.g.: Opera Ticket Pickup",
        taskDescriptionLabel = "Task Description / To-Do",
        taskDescriptionPlaceholder = "E.g.: Pick up reserved tickets from the box office",
        placeNameLabel = "Location / Place Name",
        placeNamePlaceholder = "E.g.: City Theater, Office Tower...",
        addressLabel = "Address",
        categoryLabel = "Category",
        radiusLabel = "Arrival Geofence Radius",
        searchGoogleMaps = "Find on Google Maps",
        searching = "Searching location...",
        pinOnMap = "Pin on Map",
        save = "Save Task",
        cancel = "Cancel",
        emptyTitle = "No location tasks added yet",
        emptySubtitle = "Add places like your workplace, park, theater, or grocery store; get notified automatically upon arrival!",
        emptyAction = "+ Add Your First Task",
        permissionTitle = "📍 Location Permission Needed",
        permissionSubtitle = "To receive automatic background notifications when arriving at places, please grant location access.",
        permissionButton = "Enable Location Access",
        trackingTitle = "Background Location Monitor",
        trackingActive = "Active (Every 10s)",
        trackingInactive = "Paused",
        trackingIntervalInfo = "Current location is compared with task geofences every 10 seconds.",
        testArrival = "Test Arrival",
        openInGoogleMaps = "Open in Google Maps",
        searchPlaceholder = "Search task, place, or address...",
        filterAll = "All",
        tasksCount = "Active Tasks",
        completedCount = "Completed",
        meterUnit = "m",
        simulatedArrivalToast = "arrival simulated! Notification delivered.",
        deleteConfirm = "Are you sure you want to delete this task?",
        proximitySettingTitle = "Map Proximity Alert Range",
        proximitySettingSubtitle = "When map is opened, to-do tasks within this distance are displayed and a route is shown.",
        nearbyAlertTitle = "Task Nearby To Do!",
        nearbyAlertSubtitle = "within configured proximity",
        showRouteButton = "Show Route on Map",
        openMapsNavigation = "Navigate in Google Maps",
        currentLocationLabel = "Current Location",
        targetLocationLabel = "Target Task Location",
        walkTimeEstimate = "walking distance",
        noNearbyTasksFound = "No active tasks found within this distance.",
        tabArchive = "Archive",
        archiveTitle = "Completed Tasks Archive",
        archiveSubtitle = "History of finished location-based reminders.",
        archiveEmptyTitle = "No Archived Tasks",
        archiveEmptySubtitle = "Completed location reminders are automatically stored here.",
        restoreTask = "Restore to Active",
        clearArchive = "Clear Archive",
        clearArchiveConfirm = "Permanently delete all completed tasks from archive?",
        deletePermanently = "Delete Permanently",
        themeSettingTitle = "App Theme",
        themeSettingSubtitle = "Switch between light, dark, or system default mode.",
        themeSystem = "System Default",
        themeLight = "Light Mode",
        themeDark = "Dark Mode",
        hapticDeleteTip = "Long-press trash icon or card to delete with tactile feedback.",
        placeNotFoundMessage = { query -> "Location could not be found for '$query'. Please verify the place name or pick the pin on the map." },
        placeFoundSuccess = "Location found and coordinates resolved!",
        placeLocationNotSetWarning = "Location coordinates could not be resolved for this place. Please search for the place or select it on the map.",
        resolveLocation = "Locate Place"
    )

    val turkish = LocalizedStrings(
        appTitle = "Konum Görev Yöneticisi",
        appSubtitle = "Akıllı Konum & Görev Takibi",
        tabMap = "Harita",
        tabTasks = "Görevler",
        tabSync = "Senkron",
        settings = "Ayarlar",
        language = "Uygulama Dili",
        languageSubtitle = "Uygulama arayüz dilini anında değiştirin",
        languageSelectHint = "Aşağıdaki listeden dilediğiniz dili seçin",
        priority = "Öncelik",
        priorityHigh = "Yüksek",
        priorityMedium = "Orta",
        priorityLow = "Düşük",
        enterKeyNewEntry = "⏎ Yeni Giriş Yap",
        selectedTaskBanner = "Seçili Görev",
        clearSelection = "Seçimi Kaldır",
        addNewTask = "Yeni Konum Görevi",
        editTask = "Görevi Düzenle",
        taskTitleLabel = "Görev Başlığı",
        taskTitlePlaceholder = "Örn: Süreyya Tiyatrosu Bilet Teslimatı",
        taskDescriptionLabel = "Yapılacak İşlem / Açıklama",
        taskDescriptionPlaceholder = "Örn: Gişeden cuma günkü rezerve biletleri al",
        placeNameLabel = "Konum / Yer Adı",
        placeNamePlaceholder = "Örn: Kadıköy Süreyya Tiyatrosu, Maslak Ofis...",
        addressLabel = "Açık Adres",
        categoryLabel = "Kategori",
        radiusLabel = "Varış Bildirim Yarıçapı",
        searchGoogleMaps = "Google Haritalar'da Bul",
        searching = "Konum aranıyor...",
        pinOnMap = "Haritada Konum İğnele",
        save = "Görevi Kaydet",
        cancel = "İptal",
        emptyTitle = "Henüz bir konum görevi eklenmedi",
        emptySubtitle = "İşyeriniz, park, tiyatro veya market gibi sık gittiğiniz yerleri ekleyin; oraya vardığınızda uygulama size bildirimle hatırlatsın!",
        emptyAction = "+ İlk Görevinizi Ekleyin",
        permissionTitle = "📍 Konum İzni Gerekli",
        permissionSubtitle = "Belirlediğiniz konumlara vardığınızda görevlerinizi arka planda bildirebilmek için konum erişimine izin verilmelidir.",
        permissionButton = "Konum İznini Etkinleştir",
        trackingTitle = "Arka Plan Konum İzleme",
        trackingActive = "Aktif (10 sn aralıkla)",
        trackingInactive = "Durduruldu",
        trackingIntervalInfo = "Mevcut konumunuz her 10 saniyede bir görev konumlarıyla karşılaştırılır.",
        testArrival = "Varışı Test Et",
        openInGoogleMaps = "Google Haritalar'da Aç",
        searchPlaceholder = "Görev, yer adı veya adres ara...",
        filterAll = "Tümü",
        tasksCount = "Aktif Görev",
        completedCount = "Tamamlanan",
        meterUnit = "m",
        simulatedArrivalToast = "konumuna varış simüle edildi! Bildirim gönderildi.",
        deleteConfirm = "Bu görevi silmek istediğinize emin misiniz?",
        proximitySettingTitle = "Harita Yakınlık Bildirim Mesafesi",
        proximitySettingSubtitle = "Harita seçildiğinde bu mesafe içindeki yapılacak işler ekranda gösterilir ve rota çizilir.",
        nearbyAlertTitle = "Yakınınızda Yapılacak İş Var!",
        nearbyAlertSubtitle = "belirlenen yakınlık mesafesinde",
        showRouteButton = "Rotayı / Yolu Göster",
        openMapsNavigation = "Google Haritalar ile Git",
        currentLocationLabel = "Bulunduğunuz Yer",
        targetLocationLabel = "Hedef Görev Konumu",
        walkTimeEstimate = "yürüme mesafesinde",
        noNearbyTasksFound = "Bu mesafe içinde aktif görev bulunamadı.",
        tabArchive = "Arşiv",
        archiveTitle = "Tamamlanan Görevler Arşivi",
        archiveSubtitle = "Daha önce tamamladığınız konum bazlı hatırlatıcıların geçmişi.",
        archiveEmptyTitle = "Arşivde Görev Yok",
        archiveEmptySubtitle = "Bir görevi tamamladığınızda otomatik olarak bu arşive kaydedilir.",
        restoreTask = "Aktife Döndür",
        clearArchive = "Arşivi Temizle",
        clearArchiveConfirm = "Tamamlanmış tüm görevler arşivden kalıcı olarak silinsin mi?",
        deletePermanently = "Kalıcı Olarak Sil",
        themeSettingTitle = "Uygulama Teması",
        themeSettingSubtitle = "Açık, koyu veya sistem teması arasında geçiş yapın.",
        themeSystem = "Sistem Varsayılanı",
        themeLight = "Açık Tema",
        themeDark = "Koyu Tema",
        hapticDeleteTip = "Silmek için çöp kutusu simgesine veya karta basılı tutun.",
        placeNotFoundMessage = { query -> "'$query' yeri bulunamadı. Lütfen yer adını kontrol edin veya harita üzerinden konumu işaretleyin." },
        placeFoundSuccess = "Konum bulundu ve koordinatlar başarıyla işlendi!",
        placeLocationNotSetWarning = "Bu yer için konum bulunamadı. Lütfen yer araması yapın veya harita üzerinden konumu seçin.",
        resolveLocation = "Konumu Bul"
    )

    val spanish = LocalizedStrings(
        appTitle = "Administrador de Tareas por Ubicación",
        appSubtitle = "Recordatorio Inteligente de Tareas y Lugares",
        tabMap = "Mapa",
        tabTasks = "Tareas",
        tabSync = "Sincronizar",
        settings = "Ajustes",
        language = "Idioma de la Aplicación",
        languageSubtitle = "Cambia el idioma de la interfaz al instante",
        languageSelectHint = "Elige tu idioma preferido de la lista",
        priority = "Prioridad",
        priorityHigh = "Alta",
        priorityMedium = "Media",
        priorityLow = "Baja",
        enterKeyNewEntry = "⏎ Nueva Entrada",
        selectedTaskBanner = "Tarea Seleccionada",
        clearSelection = "Deseleccionar",
        addNewTask = "Nueva Tarea de Ubicación",
        editTask = "Editar Tarea",
        taskTitleLabel = "Título de la Tarea",
        taskTitlePlaceholder = "Ej: Recoger entradas de teatro",
        taskDescriptionLabel = "Descripción / Qué Hacer",
        taskDescriptionPlaceholder = "Ej: Retirar las entradas reservadas en taquilla",
        placeNameLabel = "Lugar / Nombre del Sitio",
        placeNamePlaceholder = "Ej: Teatro Municipal, Oficina...",
        addressLabel = "Dirección",
        categoryLabel = "Categoría",
        radiusLabel = "Radio de Geovalla de Llegada",
        searchGoogleMaps = "Buscar en Google Maps",
        searching = "Buscando ubicación...",
        pinOnMap = "Fijar en el Mapa",
        save = "Guardar Tarea",
        cancel = "Cancelar",
        emptyTitle = "Aún no hay tareas de ubicación",
        emptySubtitle = "Añade lugares como tu oficina, parque o mercado; ¡recibe alertas al llegar!",
        emptyAction = "+ Añade tu Primera Tarea",
        permissionTitle = "📍 Permiso de Ubicación Requerido",
        permissionSubtitle = "Para notificarte en segundo plano al llegar a un lugar, concede permiso de ubicación.",
        permissionButton = "Activar Permiso de Ubicación",
        trackingTitle = "Monitoreo en Segundo Plano",
        trackingActive = "Activo (cada 10s)",
        trackingInactive = "Pausado",
        trackingIntervalInfo = "La ubicación actual se verifica cada 10 segundos.",
        testArrival = "Simular Llegada",
        openInGoogleMaps = "Abrir en Google Maps",
        searchPlaceholder = "Buscar tarea, lugar o dirección...",
        filterAll = "Todos",
        tasksCount = "Tareas Activas",
        completedCount = "Completadas",
        meterUnit = "m",
        simulatedArrivalToast = "¡llegada simulada con éxito! Notificación enviada.",
        deleteConfirm = "¿Seguro que deseas eliminar esta tarea?",
        proximitySettingTitle = "Rango de Alerta de Proximidad",
        proximitySettingSubtitle = "Al abrir el mapa se mostrarán las tareas pendientes dentro de esta distancia.",
        nearbyAlertTitle = "¡Tienes Tareas Pendientes Cerca!",
        nearbyAlertSubtitle = "dentro de la distancia configurada",
        showRouteButton = "Mostrar Ruta en el Mapa",
        openMapsNavigation = "Navegar con Google Maps",
        currentLocationLabel = "Ubicación Actual",
        targetLocationLabel = "Ubicación de la Tarea",
        walkTimeEstimate = "a pie",
        noNearbyTasksFound = "No se encontraron tareas dentro de esta distancia.",
        tabArchive = "Archivo",
        archiveTitle = "Archivo de Tareas Completadas",
        archiveSubtitle = "Historial de recordatorios ya finalizados.",
        archiveEmptyTitle = "Archivo Vacío",
        archiveEmptySubtitle = "Las tareas completadas se archivan automáticamente aquí.",
        restoreTask = "Restaurar a Activa",
        clearArchive = "Vaciar Archivo",
        clearArchiveConfirm = "¿Eliminar todas las tareas archivadas definitivamente?",
        deletePermanently = "Eliminar Definitivamente",
        themeSettingTitle = "Tema de la Aplicación",
        themeSettingSubtitle = "Cambia entre claro, oscuro o predeterminado del sistema.",
        themeSystem = "Predeterminado del Sistema",
        themeLight = "Modo Claro",
        themeDark = "Modo Oscuro",
        hapticDeleteTip = "Mantén presionado el icono o la tarjeta para eliminar.",
        placeNotFoundMessage = { query -> "No se encontró la ubicación de '$query'. Por favor verifique el nombre o selecciónela en el mapa." },
        placeFoundSuccess = "¡Ubicación encontrada y coordenadas aplicadas!",
        placeLocationNotSetWarning = "No se pudieron resolver las coordenadas. Por favor busque el lugar o selecciónelo en el mapa.",
        resolveLocation = "Ubicar Lugar"
    )

    val german = LocalizedStrings(
        appTitle = "Standort Aufgabenplaner",
        appSubtitle = "Intelligente ortsbasierte Erinnerungen",
        tabMap = "Karte",
        tabTasks = "Aufgaben",
        tabSync = "Sync",
        settings = "Einstellungen",
        language = "App-Sprache",
        languageSubtitle = "Ändern Sie die Benutzeroberfläche sofort",
        languageSelectHint = "Wählen Sie Ihre bevorzugte Sprache aus",
        priority = "Priorität",
        priorityHigh = "Hoch",
        priorityMedium = "Mittel",
        priorityLow = "Niedrig",
        enterKeyNewEntry = "⏎ Neuer Eintrag",
        selectedTaskBanner = "Ausgewählte Aufgabe",
        clearSelection = "Auswahl aufheben",
        addNewTask = "Neue Standort-Aufgabe",
        editTask = "Aufgabe bearbeiten",
        taskTitleLabel = "Aufgabentitel",
        taskTitlePlaceholder = "Z.B.: Theaterkarten abholen",
        taskDescriptionLabel = "Beschreibung / Was zu tun ist",
        taskDescriptionPlaceholder = "Z.B.: Reservierte Karten an der Kasse abholen",
        placeNameLabel = "Ort / Name des Standorts",
        placeNamePlaceholder = "Z.B.: Stadttheater, Hauptbüro...",
        addressLabel = "Adresse",
        categoryLabel = "Kategorie",
        radiusLabel = "Ankunftsradius",
        searchGoogleMaps = "In Google Maps suchen",
        searching = "Standort wird gesucht...",
        pinOnMap = "Auf Karte markieren",
        save = "Aufgabe speichern",
        cancel = "Abbrechen",
        emptyTitle = "Noch keine Aufgaben hinzugefügt",
        emptySubtitle = "Fügen Sie Orte wie Büro, Theater oder Markt hinzu; Benachrichtigung bei Ankunft!",
        emptyAction = "+ Erste Aufgabe hinzufügen",
        permissionTitle = "📍 Standortberechtigung erforderlich",
        permissionSubtitle = "Für automatische Benachrichtigungen bei Ankunft am Standort.",
        permissionButton = "Standort aktivieren",
        trackingTitle = "Hintergrund-Überwachung",
        trackingActive = "Aktiv (alle 10 Sek.)",
        trackingInactive = "Pausiert",
        trackingIntervalInfo = "Aktueller Standort wird alle 10 Sekunden geprüft.",
        testArrival = "Ankunft testen",
        openInGoogleMaps = "In Google Maps öffnen",
        searchPlaceholder = "Aufgabe, Ort oder Adresse suchen...",
        filterAll = "Alle",
        tasksCount = "Aktive Aufgaben",
        completedCount = "Erledigt",
        meterUnit = "m",
        simulatedArrivalToast = "Ankunft simuliert! Benachrichtigung gesendet.",
        deleteConfirm = "Möchten Sie diese Aufgabe wirklich löschen?",
        proximitySettingTitle = "Karten-Näherungsradius",
        proximitySettingSubtitle = "Aufgaben innerhalb dieser Entfernung werden auf der Karte angezeigt.",
        nearbyAlertTitle = "Aufgabe in der Nähe zu erledigen!",
        nearbyAlertSubtitle = "innerhalb der konfigurierten Entfernung",
        showRouteButton = "Route anzeigen",
        openMapsNavigation = "Mit Google Maps navigieren",
        currentLocationLabel = "Aktueller Standort",
        targetLocationLabel = "Zielstandort",
        walkTimeEstimate = "Gehzeit",
        noNearbyTasksFound = "Keine aktiven Aufgaben in dieser Entfernung gefunden.",
        tabArchive = "Archiv",
        archiveTitle = "Archiv erledigter Aufgaben",
        archiveSubtitle = "Verlauf erledigter ortsbezogener Aufgaben.",
        archiveEmptyTitle = "Keine archivierten Aufgaben",
        archiveEmptySubtitle = "Erledigte Aufgaben werden automatisch hier gespeichert.",
        restoreTask = "Wiederherstellen",
        clearArchive = "Archiv leeren",
        clearArchiveConfirm = "Alle archivierten Aufgaben dauerhaft löschen?",
        deletePermanently = "Dauerhaft löschen",
        themeSettingTitle = "App-Design",
        themeSettingSubtitle = "Wechseln Sie zwischen Hell, Dunkel oder System.",
        themeSystem = "Systemstandard",
        themeLight = "Helles Design",
        themeDark = "Dunkles Design",
        hapticDeleteTip = "Lange auf das Symbol oder die Karte drücken zum Löschen.",
        placeNotFoundMessage = { query -> "Standort für '$query' wurde nicht gefunden. Bitte überprüfen Sie den Namen oder wählen Sie ihn auf der Karte." },
        placeFoundSuccess = "Standort gefunden und Koordinaten aktualisiert!",
        placeLocationNotSetWarning = "Koordinaten konnten nicht ermittelt werden. Bitte suchen Sie den Ort oder wählen Sie ihn auf der Karte.",
        resolveLocation = "Ort lokalisieren"
    )

    val french = LocalizedStrings(
        appTitle = "Gestionnaire de Tâches par Emplacement",
        appSubtitle = "Rappels Intelligents Basés sur la Localisation",
        tabMap = "Carte",
        tabTasks = "Tâches",
        tabSync = "Synchro",
        settings = "Paramètres",
        language = "Langue de l'application",
        languageSubtitle = "Changez la langue de l'interface instantanément",
        languageSelectHint = "Choisissez votre langue préférée dans la liste",
        priority = "Priorité",
        priorityHigh = "Haute",
        priorityMedium = "Moyenne",
        priorityLow = "Basse",
        enterKeyNewEntry = "⏎ Nouvelle entrée",
        selectedTaskBanner = "Tâche sélectionnée",
        clearSelection = "Désélectionner",
        addNewTask = "Nouvelle tâche de lieu",
        editTask = "Modifier la tâche",
        taskTitleLabel = "Titre de la tâche",
        taskTitlePlaceholder = "Ex : Retrait des billets de théâtre",
        taskDescriptionLabel = "Description / À faire",
        taskDescriptionPlaceholder = "Ex : Récupérer les billets réservés au guichet",
        placeNameLabel = "Nom du lieu",
        placeNamePlaceholder = "Ex : Théâtre municipal, Bureau...",
        addressLabel = "Adresse",
        categoryLabel = "Catégorie",
        radiusLabel = "Rayon de notification d'arrivée",
        searchGoogleMaps = "Chercher sur Google Maps",
        searching = "Recherche de lieu...",
        pinOnMap = "Épingler sur la carte",
        save = "Enregistrer la tâche",
        cancel = "Annuler",
        emptyTitle = "Aucune tâche pour le moment",
        emptySubtitle = "Ajoutez des lieux clés ; recevez une notification automatique à votre arrivée !",
        emptyAction = "+ Ajouter votre première tâche",
        permissionTitle = "📍 Autorisation de localisation requise",
        permissionSubtitle = "Pour recevoir des notifications d'arrivée en arrière-plan.",
        permissionButton = "Activer la localisation",
        trackingTitle = "Surveillance en arrière-plan",
        trackingActive = "Actif (toutes les 10s)",
        trackingInactive = "En pause",
        trackingIntervalInfo = "Position vérifiée toutes les 10 secondes.",
        testArrival = "Tester l'arrivée",
        openInGoogleMaps = "Ouvrir dans Google Maps",
        searchPlaceholder = "Rechercher une tâche, un lieu ou une adresse...",
        filterAll = "Tous",
        tasksCount = "Tâches actives",
        completedCount = "Terminées",
        meterUnit = "m",
        simulatedArrivalToast = "Arrivée simulée ! Notification envoyée.",
        deleteConfirm = "Voulez-vous vraiment supprimer cette tâche ?",
        proximitySettingTitle = "Distance d'alerte de proximité",
        proximitySettingSubtitle = "Affiche les tâches et trace l'itinéraire dans ce rayon.",
        nearbyAlertTitle = "Tâche à faire à proximité !",
        nearbyAlertSubtitle = "dans le rayon configuré",
        showRouteButton = "Afficher l'itinéraire",
        openMapsNavigation = "Naviguer avec Google Maps",
        currentLocationLabel = "Position actuelle",
        targetLocationLabel = "Emplacement de la tâche",
        walkTimeEstimate = "à pied",
        noNearbyTasksFound = "Aucune tâche active trouvée dans cette zone.",
        tabArchive = "Archive",
        archiveTitle = "Archives des tâches terminées",
        archiveSubtitle = "Historique des rappels géolocalisés terminés.",
        archiveEmptyTitle = "Aucune tâche archivée",
        archiveEmptySubtitle = "Les tâches terminées sont automatiquement stockées ici.",
        restoreTask = "Rétablir",
        clearArchive = "Vider l'archive",
        clearArchiveConfirm = "Supprimer définitivement toutes les tâches archivées ?",
        deletePermanently = "Supprimer définitivement",
        themeSettingTitle = "Thème de l'application",
        themeSettingSubtitle = "Basculez entre clair, sombre ou système.",
        themeSystem = "Thème du système",
        themeLight = "Thème clair",
        themeDark = "Thème sombre",
        hapticDeleteTip = "Appui long sur l'icône ou la carte pour supprimer.",
        placeNotFoundMessage = { query -> "L'emplacement pour '$query' est introuvable. Veuillez vérifier le nom ou sélectionner sur la carte." },
        placeFoundSuccess = "Emplacement trouvé et coordonnées appliquées !",
        placeLocationNotSetWarning = "Les coordonnées n'ont pas pu être déterminées. Veuillez rechercher le lieu ou le sélectionner sur la carte.",
        resolveLocation = "Localiser le lieu"
    )

    fun getStrings(language: AppLanguage): LocalizedStrings {
        return when (language) {
            AppLanguage.ENGLISH -> english
            AppLanguage.TURKISH -> turkish
            AppLanguage.SPANISH -> spanish
            AppLanguage.GERMAN -> german
            AppLanguage.FRENCH -> french
        }
    }
}

